"""
Churn Detection — 2-Month Look-back (Buffer)
=============================================
Loads all *_active.csv files produced by prime_data_cleaning.py,
sorts them chronologically, and flags every CUSTOMER_ID that
appeared in ANY earlier month but is ABSENT from BOTH of the
last TWO files as churned.

This provides a more conservative churn definition: a customer
must be missing for two consecutive months before being labelled
as churned, reducing false positives from temporary drop-outs.
"""

import pandas as pd
import numpy as np
import glob
import os
import re
from datetime import datetime


# Column names
CUSTOMER_ID_COL = "CUSTOMER_ID"    # generated by prime_data_cleaning.py
CHURN_COL       = "CHURN"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

month_map = {
    "JAN": 1, "FEB": 2, "MAR": 3, "APR": 4,
    "MAY": 5, "JUN": 6, "JUL": 7, "AUG": 8,
    "SEP": 9, "OCT": 10, "NOV": 11, "DEC": 12
}


def get_month_year(file_path):
    """
    Extracts proper datetime from filename like:
    cleaned_JUL_2025.csv
    """
    name = os.path.basename(file_path).upper()
    match = re.search(r"(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)_(\d{4})", name)

    if match:
        month = month_map[match.group(1)]
        year = int(match.group(2))
        return datetime(year, month, 1)

    # fallback very early date
    return datetime(1900, 1, 1)


def get_month_label(file_path):
    """Return a human-readable label like '2025-JUL'."""
    name = os.path.basename(file_path).upper()
    match = re.search(r"(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)_(\d{4})", name)
    if match:
        return f"{match.group(2)}-{match.group(1)}"
    return os.path.splitext(os.path.basename(file_path))[0]


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
INPUT_DIR  = "prime_cleaned"
OUTPUT_DIR = "churn_output"
os.makedirs(OUTPUT_DIR, exist_ok=True)


# ---------------------------------------------------------------------------
# 1. Discover and sort active files chronologically
# ---------------------------------------------------------------------------
active_files = sorted(
    glob.glob(os.path.join(INPUT_DIR, "*_active.csv")),
    key=get_month_year,
)

if len(active_files) < 3:
    print("ERROR: Need at least 3 active files for 2-month look-back churn detection.")
    exit(1)

print(f"Found {len(active_files)} active file(s), sorted chronologically:\n")
for f in active_files:
    print(f"  {get_month_label(f)}  ->  {f}")


# ---------------------------------------------------------------------------
# 2. Load the LAST TWO files (reference window)
# ---------------------------------------------------------------------------
last_file       = active_files[-1]
second_last_file = active_files[-2]
last_label       = get_month_label(last_file)
second_last_label = get_month_label(second_last_file)

print(f"\nReference window:")
print(f"  Month T   (latest)       : {last_label}")
print(f"  Month T-1 (second latest): {second_last_label}\n")

# --- Load last month ---
df_last = pd.read_csv(last_file, dtype={CUSTOMER_ID_COL: "string"})
df_last[CUSTOMER_ID_COL] = df_last[CUSTOMER_ID_COL].str.strip()
last_ids = set(df_last[CUSTOMER_ID_COL].dropna().unique())

# --- Load second-to-last month ---
df_second = pd.read_csv(second_last_file, dtype={CUSTOMER_ID_COL: "string"})
df_second[CUSTOMER_ID_COL] = df_second[CUSTOMER_ID_COL].str.strip()
second_ids = set(df_second[CUSTOMER_ID_COL].dropna().unique())

# Union of customers present in EITHER of the last two months
buffer_ids = last_ids | second_ids

print(f"  Unique customers in {last_label}       : {len(last_ids)}")
print(f"  Unique customers in {second_last_label} : {len(second_ids)}")
print(f"  Union (buffer window)                   : {len(buffer_ids)}")


# ---------------------------------------------------------------------------
# 3. Build a pool of ALL customer IDs from months BEFORE the buffer window
# ---------------------------------------------------------------------------
earlier_files = active_files[:-2]

customer_last_seen = {}   # CUSTOMER_ID -> label of last file they appeared in

for f in earlier_files:
    label = get_month_label(f)
    df = pd.read_csv(f, dtype={CUSTOMER_ID_COL: "string"})
    df[CUSTOMER_ID_COL] = df[CUSTOMER_ID_COL].str.strip()

    for cid in df[CUSTOMER_ID_COL].dropna().unique():
        customer_last_seen[cid] = label

all_earlier_ids = set(customer_last_seen.keys())
print(f"  Unique customers across earlier months : {len(all_earlier_ids)}")


# ---------------------------------------------------------------------------
# 4. Identify churned customers
#    Churned = appeared before the buffer window AND missing from BOTH
#              of the last two months
# ---------------------------------------------------------------------------
churned_ids = all_earlier_ids - buffer_ids
print(f"\n  Churned customers (missing from both {second_last_label} & {last_label}): {len(churned_ids)}")

# Build the output dataframe
records = []
for cid in sorted(churned_ids):
    last_month = customer_last_seen.get(cid, "UNKNOWN")
    records.append({
        CUSTOMER_ID_COL: cid,
        "LAST_SEEN":     last_month,
        CHURN_COL:       1,
    })

churned_df = pd.DataFrame(records)


# ---------------------------------------------------------------------------
# 5. Tag non-churned customers
# ---------------------------------------------------------------------------
# Customers from earlier months that ARE in at least one of the last two
active_ids = all_earlier_ids & buffer_ids
active_records = []
for cid in sorted(active_ids):
    # Determine which recent month(s) they appear in
    in_last   = cid in last_ids
    in_second = cid in second_ids

    if in_last and in_second:
        seen_label = f"{second_last_label} & {last_label}"
    elif in_last:
        seen_label = last_label
    else:
        seen_label = second_last_label

    active_records.append({
        CUSTOMER_ID_COL: cid,
        "LAST_SEEN":     seen_label,
        CHURN_COL:       0,
    })

active_df = pd.DataFrame(active_records)

# Combine
result_df = pd.concat([churned_df, active_df], ignore_index=True)


# ---------------------------------------------------------------------------
# 6. Save
# ---------------------------------------------------------------------------
out_path = os.path.join(OUTPUT_DIR, "churn_2month_lookback.csv")
result_df.to_csv(out_path, index=False)

print(f"\n{'='*60}")
print(f"Results saved to: {out_path}")
print(f"  Total customers tracked : {len(result_df)}")
print(f"  Churned                 : {len(churned_df)}")
print(f"  Still active            : {len(active_df)}")
print(f"{'='*60}\n")

